---
title: "Figure2"
author: "Lukas"
date: '2022-06-13'
output: html_document
---t
---

# Load packages

```{r}
library("tidyverse")
library("psych")
library("pheatmap")
library("ggpubr")
library("patchwork")
library("ghibli")
library("reprex")
library("ggh4x")
library("ggplot2")
lit_path <-"C:/Users/lukwolt/Documents/R/LIT/"
ot_path <-"C:/Users/lukwolt/Documents/R/OT/"

ghibli_palettes$YesterdayMedium

```

# Load data 20SPD

1 ng
```{r}
#34w
LITDIA_Normal_20SPD_34w_1 <- read.csv2(paste0(lit_path, "20220218_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_auto_34w.csv"))
#40w
LITDIA_Normal_20SPD_40w_1 <- read.csv2(paste0(lit_path, "20220502_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_auto.csv"))
#45w
LITDIA_Normal_20SPD_45w_1 <- read.csv2(paste0(lit_path, "20220218_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_auto_45w.csv"))
```

100 ng
```{r}
#34w
LITDIA_Normal_20SPD_34w_100 <- read.csv2(paste0(lit_path, "20220418_LIT_Normal_DIA_100ng_20SPD_whisper100_1CV_auto_34w.csv"))
#40w
LITDIA_Normal_20SPD_40w_100 <- read.csv2(paste0(lit_path, "20220413_LIT_Normal_DIA_100ng_20SPD_whisper100_1CV_auto_40w.csv"))
#45w
LITDIA_Normal_20SPD_45w_100 <- read.csv2(paste0(lit_path, "20220418_LIT_Normal_DIA_100ng_20SPD_whisper100_1CV_auto_45w.csv"))
```

# Load data 40SPD
1 ng
```{r}
#34w
LITDIA_Normal_34w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_1ng_40SPD_whisper100_1CV_auto_34w.csv"))
#40w
LITDIA_Normal_40w_1 <- read.csv2(paste0(lit_path, "20220421_LIT_Normal_DIA_1ng_40SPD_whisper100_1CV_auto.csv"))
#45w
LITDIA_Normal_45w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_1ng_40SPD_whisper100_1CV_auto_45w.csv"))
```

100 ng
```{r}
#34w
LITDIA_Normal_34w_100 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_100ng_40SPD_whisper100_1CV_auto_34w.csv"))
#40w
LITDIA_Normal_40w_100 <- read.csv2(paste0(lit_path, "20220421_LIT_Normal_DIA_100ng_40SPD_whisper100_1CV_auto.csv"))
#45w
LITDIA_Normal_45w_100 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_100ng_40SPD_whisper100_1CV_auto_45w.csv"))
```

# Remove peptides found in less than 3 replicates
```{r}
filter_pep <- function(x) {
  x$FG.Quantity[as.logical(x$EG.IsImputed)] <- NA
  y <- x %>% 
  group_by(R.FileName, PEP.StrippedSequence) %>% 
  summarise(mean_quantity = mean(FG.Quantity, na.rm = TRUE)) %>%  
  pivot_wider(names_from = R.FileName, 
              values_from = mean_quantity) %>%
    suppressMessages()
  z <- y %>% 
  mutate(na_nbr = rowSums(is.na(y[-1]))) %>%
  mutate(mean_quantity = rowMeans(y[2:ncol(y)], na.rm = TRUE)) %>%
  mutate(filtered = !na_nbr <= 1) %>% 
  select(-na_nbr) %>% 
  suppressMessages("`summarise()` has grouped output by 'R.FileName'. You can override using the `.groups` argument.")
  message("Highlighted ", sum(z$filtered), " peptide(s) found in less than ", ncol(y) -2, " replicates")
  
 return(z) }

```

20 SPD
1 ng
```{r}
#34w
LITDIA_Normal_20SPD_34w_1 <-  filter_pep(LITDIA_Normal_20SPD_34w_1)
LITDIA_Normal_20SPD_34w_1_filter <- LITDIA_Normal_20SPD_34w_1[LITDIA_Normal_20SPD_34w_1$filtered == FALSE, ]
#40w
LITDIA_Normal_20SPD_40w_1 <-  filter_pep(LITDIA_Normal_20SPD_40w_1)
LITDIA_Normal_20SPD_40w_1_filter <- LITDIA_Normal_20SPD_40w_1[LITDIA_Normal_20SPD_40w_1$filtered == FALSE, ]
#45w
LITDIA_Normal_20SPD_45w_1 <-  filter_pep(LITDIA_Normal_20SPD_45w_1)
LITDIA_Normal_20SPD_45w_1_filter <- LITDIA_Normal_20SPD_45w_1[LITDIA_Normal_20SPD_45w_1$filtered == FALSE, ]
```

100 ng
```{r}
#34w
LITDIA_Normal_20SPD_34w_100 <-  filter_pep(LITDIA_Normal_20SPD_34w_100)
LITDIA_Normal_20SPD_34w_100_filter <- LITDIA_Normal_20SPD_34w_100[LITDIA_Normal_20SPD_34w_100$filtered == FALSE, ]
#40w
LITDIA_Normal_20SPD_40w_100 <-  filter_pep(LITDIA_Normal_20SPD_40w_100)
LITDIA_Normal_20SPD_40w_100_filter <- LITDIA_Normal_20SPD_40w_100[LITDIA_Normal_20SPD_40w_100$filtered == FALSE, ]
#45w
LITDIA_Normal_20SPD_45w_100 <-  filter_pep(LITDIA_Normal_20SPD_45w_100)
LITDIA_Normal_20SPD_45w_100_filter <- LITDIA_Normal_20SPD_45w_100[LITDIA_Normal_20SPD_45w_100$filtered == FALSE, ]
```

40 SPD
1 ng
```{r}
LITDIA_Normal_34w_1 <-  filter_pep(LITDIA_Normal_34w_1)
LITDIA_Normal_34w_1_filter <- LITDIA_Normal_34w_1[LITDIA_Normal_34w_1$filtered == FALSE, ]
LITDIA_Normal_40w_1 <-  filter_pep(LITDIA_Normal_40w_1)
LITDIA_Normal_40w_1_filter <- LITDIA_Normal_40w_1[LITDIA_Normal_40w_1$filtered == FALSE, ]
LITDIA_Normal_45w_1 <-  filter_pep(LITDIA_Normal_45w_1)
LITDIA_Normal_45w_1_filter <- LITDIA_Normal_45w_1[LITDIA_Normal_45w_1$filtered == FALSE, ]
```

100 ng
```{r}
LITDIA_Normal_34w_100 <-  filter_pep(LITDIA_Normal_34w_100)
LITDIA_Normal_34w_100_filter <- LITDIA_Normal_34w_100[LITDIA_Normal_34w_100$filtered == FALSE, ]
LITDIA_Normal_40w_100 <-  filter_pep(LITDIA_Normal_40w_100)
LITDIA_Normal_40w_100_filter <- LITDIA_Normal_40w_100[LITDIA_Normal_40w_100$filtered == FALSE, ]
LITDIA_Normal_45w_100 <-  filter_pep(LITDIA_Normal_45w_100)
LITDIA_Normal_45w_100_filter <- LITDIA_Normal_45w_100[LITDIA_Normal_45w_100$filtered == FALSE, ]
```

# Detect the number of identified peptides
```{r}
id_LITDIA_Normal_20SPD_34w_1 <- id_LITDIA_Normal_20SPD_40w_1 <- id_LITDIA_Normal_20SPD_45w_1 <- 
  id_LITDIA_Normal_20SPD_34w_100 <- id_LITDIA_Normal_20SPD_40w_100 <- id_LITDIA_Normal_20SPD_45w_100 <- id_LITDIA_Normal_34w_1 <- id_LITDIA_Normal_40w_1 <- id_LITDIA_Normal_45w_1 <- 
  id_LITDIA_Normal_34w_100 <- id_LITDIA_Normal_40w_100 <- id_LITDIA_Normal_45w_100 <- rep(NA, 4)
```

20 SPD
1 ng
34w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_34w_1[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_34w_1[, i]))}
```
40w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_40w_1[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_40w_1[, i]))}
```
45w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_45w_1[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_45w_1[, i]))}
```

100 ng
34w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_34w_100[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_34w_100[, i]))}
```
40w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_40w_100[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_40w_100[, i]))}
```
45w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_20SPD_45w_100[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_45w_100[, i]))}
```

id 40 SPD
1 ng
34w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_34w_1[i-1] <- sum(!is.na(LITDIA_Normal_34w_1[, i]))}
```
40w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_40w_1[i-1] <- sum(!is.na(LITDIA_Normal_40w_1[, i]))}
```
45w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_45w_1[i-1] <- sum(!is.na(LITDIA_Normal_45w_1[, i]))}
```

100 ng
34w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_34w_100[i-1] <- sum(!is.na(LITDIA_Normal_34w_100[, i]))}
```

40w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_40w_100[i-1] <- sum(!is.na(LITDIA_Normal_40w_100[, i]))}
```

45w
```{r}
for(i in 2:5){
  id_LITDIA_Normal_45w_100[i-1] <- sum(!is.na(LITDIA_Normal_45w_100[, i]))}
```

# Complement the table
```{r}
compute_CV <- function(x){
  y <- x %>% 
    mutate(sd = apply(x[, 2:(ncol(x)-2)],
                      FUN = sd, MARGIN =  1, na.rm = TRUE),
           CV = sd/mean_quantity)
  colnames(y)[2:(ncol(x)-2)] <- paste0("S", 1:(ncol(x)-3))
  if(ncol(x) <= 6){
  y$S4 <- NA
 }
  return(y)
}
```

20 SPD
```{r}
LITDIA_Normal_20SPD_34w_1_cv <- compute_CV(LITDIA_Normal_20SPD_34w_1)
LITDIA_Normal_20SPD_34w_1_cv$method <- "34w"
LITDIA_Normal_20SPD_34w_1_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_34w_1_cv$input<- "1 ng"


LITDIA_Normal_20SPD_34w_100_cv <- compute_CV(LITDIA_Normal_20SPD_34w_100)
LITDIA_Normal_20SPD_34w_100_cv$method <- "34w"
LITDIA_Normal_20SPD_34w_100_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_34w_100_cv$input<- "100 ng"

LITDIA_Normal_20SPD_40w_1_cv <- compute_CV(LITDIA_Normal_20SPD_40w_1)
LITDIA_Normal_20SPD_40w_1_cv$method <- "40w"
LITDIA_Normal_20SPD_40w_1_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_40w_1_cv$input<- "1 ng"

LITDIA_Normal_20SPD_40w_100_cv <- compute_CV(LITDIA_Normal_20SPD_40w_100)
LITDIA_Normal_20SPD_40w_100_cv$method <- "40w"
LITDIA_Normal_20SPD_40w_100_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_40w_100_cv$input<- "100 ng"

LITDIA_Normal_20SPD_45w_1_cv <- compute_CV(LITDIA_Normal_20SPD_45w_1)
LITDIA_Normal_20SPD_45w_1_cv$method <- "45w"
LITDIA_Normal_20SPD_45w_1_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_45w_1_cv$input<- "1 ng"

LITDIA_Normal_20SPD_45w_100_cv <- compute_CV(LITDIA_Normal_20SPD_45w_100)
LITDIA_Normal_20SPD_45w_100_cv$method <- "45w"
LITDIA_Normal_20SPD_45w_100_cv$spd<- "20SPD"
LITDIA_Normal_20SPD_45w_100_cv$input<- "100 ng"
```

40 SPD
```{r}
LITDIA_Normal_34w_1_cv <- compute_CV(LITDIA_Normal_34w_1)
LITDIA_Normal_34w_1_cv$method <- "34w"
LITDIA_Normal_34w_1_cv$spd<- "40SPD"
LITDIA_Normal_34w_1_cv$input<- "1 ng"


LITDIA_Normal_34w_100_cv <- compute_CV(LITDIA_Normal_34w_100)
LITDIA_Normal_34w_100_cv$method <- "34w"
LITDIA_Normal_34w_100_cv$spd<- "40SPD"
LITDIA_Normal_34w_100_cv$input<- "100 ng"

LITDIA_Normal_40w_1_cv <- compute_CV(LITDIA_Normal_40w_1)
LITDIA_Normal_40w_1_cv$method <- "40w"
LITDIA_Normal_40w_1_cv$spd<- "40SPD"
LITDIA_Normal_40w_1_cv$input<- "1 ng"

LITDIA_Normal_40w_100_cv <- compute_CV(LITDIA_Normal_40w_100)
LITDIA_Normal_40w_100_cv$method <- "40w"
LITDIA_Normal_40w_100_cv$spd<- "40SPD"
LITDIA_Normal_40w_100_cv$input<- "100 ng"

LITDIA_Normal_45w_1_cv <- compute_CV(LITDIA_Normal_45w_1)
LITDIA_Normal_45w_1_cv$method <- "45w"
LITDIA_Normal_45w_1_cv$spd<- "40SPD"
LITDIA_Normal_45w_1_cv$input<- "1 ng"

LITDIA_Normal_45w_100_cv <- compute_CV(LITDIA_Normal_34w_100)
LITDIA_Normal_45w_100_cv$method <- "45w"
LITDIA_Normal_45w_100_cv$spd<- "40SPD"
LITDIA_Normal_45w_100_cv$input<- "100 ng"
```

# Join to a table
```{r}
id_win <- 
  rbind(LITDIA_Normal_20SPD_34w_1_cv, LITDIA_Normal_20SPD_34w_100_cv, 
        LITDIA_Normal_20SPD_40w_1_cv, LITDIA_Normal_20SPD_40w_100_cv, 
        LITDIA_Normal_20SPD_45w_1_cv, LITDIA_Normal_20SPD_45w_100_cv, 
        LITDIA_Normal_34w_1_cv, LITDIA_Normal_34w_100_cv, 
        LITDIA_Normal_40w_1_cv, LITDIA_Normal_40w_100_cv, 
        LITDIA_Normal_45w_1_cv, LITDIA_Normal_45w_100_cv)
id_win$method %>% table()
id_win$input %>% table()
id_win$spd %>% table()

id_win$method <- factor(id_win$method, 
                          levels = unique(id_win$method))

id_win$input <- factor(id_win$input, 
                          levels = unique(id_win$input))

id_win$spd <- factor(id_win$spd, 
                          levels = unique(id_win$spd))

id_win$CV_filter <- NA
id_win$CV_filter[id_win$CV < 0.1] <- "3"
id_win$CV_filter[id_win$CV >= 0.1 & id_win$CV <= 0.15] <- "2"
id_win$CV_filter[id_win$CV > 0.15] <- "1"

id_win <- id_win %>%
  filter(!is.na(CV_filter)) %>% 
  group_by(method, spd, input, CV_filter) %>% 
  summarise(id_S1 = sum(!is.na(S1)),
            id_S2 = sum(!is.na(S2)),
            id_S3 = sum(!is.na(S3)),
            id_S4 = sum(!is.na(S4)))
id_win$id_S4[id_win$id_S4 == 0] <- NA 

id_win$mean_id <- rowMeans(id_win[5:8], na.rm = TRUE)
id_win$sd_id <- apply(id_win[5:8], FUN =  sd, MARGIN = 1, na.rm = TRUE)
```

# Plot
```{r}
id_win$y_errorbar <- id_win$mean_id
id_win$y_errorbar[id_win$CV_filter == "1"] <-
  id_win$y_errorbar[id_win$CV_filter == "1"] +
  id_win$y_errorbar[id_win$CV_filter == "2"]+
  id_win$y_errorbar[id_win$CV_filter == "3"]
id_win$y_errorbar[id_win$CV_filter == "2"] <-
  id_win$y_errorbar[id_win$CV_filter == "2"]+
  id_win$y_errorbar[id_win$CV_filter == "3"]

figure2 <- id_win %>% 
  ggplot(aes(x = method, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7) +
 facet_grid(input~spd)+
  labs(x = "Number of Windows",
       y = "Identified peptides",
       fill = "CV") +
  theme_bw() +
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 27),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.title.y = element_text(vjust = 2.2),
        axis.text.x = element_text(angle = 90, vjust = 0.3, hjust = 1),
        legend.title = element_text(size = 27),
        axis.title.x = element_text(vjust = 0.2),
        legend.text = element_text(size = 27),
        legend.key.size = unit(0.9, "cm"))+
  scale_fill_manual(values = c("grey82", "#FF9090", "#FF3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
  scale_y_continuous(limits = c(0, 16000))+
  geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.2,
                    size = 1)
cairo_pdf(filename = "fig2.pdf", width = 15.63, height = 10.94)
figure2
dev.off()
```