---
title: "Figure 8"
author: "Lukas Woltereck"
date: '2022-06-13'
output: html_document
---
# Load packages
```{r}
library("tidyverse")
library("psych")
library("pheatmap")
library("ggpubr")
library("patchwork")
library("ghibli")
library("reprex")
library("ggh4x")
library("ggplot2")
lit_path <-"C:/Users/lukwolt/Documents/R/LIT/"
ot_path <-"C:/Users/lukwolt/Documents/R/OT/"
pp_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/"
fig_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/Figures/"
dvp_path <-"C:/Users/lukwolt/Documents/R/DVP/"

ghibli_palettes$YesterdayMedium
```

# Load Data
LCM (input is surface area in cm²)
```{r}
#188
LITDIA_Enhanced_20SPD_45w_188 <- read.csv2(paste0(dvp_path, "190141_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_188.csv"))
#375
LITDIA_Enhanced_20SPD_45w_375 <- read.csv2(paste0(dvp_path, "190203_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_375.csv"))
#750
LITDIA_Enhanced_20SPD_45w_750 <- read.csv2(paste0(dvp_path, "190111_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_750.csv"))
#1500
LITDIA_Enhanced_20SPD_45w_1500 <- read.csv2(paste0(dvp_path, "190043_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_1500.csv"))
#3000
LITDIA_Enhanced_20SPD_45w_3000 <- read.csv2(paste0(dvp_path, "190018_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_3000 (2).csv"))
#6000
LITDIA_Enhanced_20SPD_45w_6000 <- read.csv2(paste0(dvp_path, "190226_HB_TP_Evo_Whisper100_20SPD_LITDIA_1CV-45_Enhanced_auto_DVP_6000.csv"))
```
HeLa
```{r}
#Enhanced 1ng
LITDIA_Enhanced_40SPD_40w_1ng_SN16 <- read.csv2(paste0(lit_path, "20220616_SN16_20SPD_LIT_Enhanced_1CV_1ng_auto_40w.csv"))
#Enhanced 5ng
LITDIA_Enhanced_40SPD_40w_5ng_SN16 <- read.csv2(paste0(lit_path, "20220616_SN16_20SPD_LIT_Enhanced_1CV_5ng_auto_40w.csv"))
#Enhanced 10ng
LITDIA_Enhanced_40SPD_40w_10ng_SN16 <- read.csv2(paste0(lit_path, "20220616_SN16_20SPD_LIT_Enhanced_1CV_10ng_auto_40w.csv"))
```

# Filter pep
```{r}
filter_pep <- function(x) {
  x$FG.Quantity[as.logical(x$EG.IsImputed)] <- NA
  y <- x %>% 
  group_by(R.FileName, PEP.StrippedSequence) %>% 
  summarise(mean_quantity = mean(FG.Quantity, na.rm = TRUE)) %>%  
  pivot_wider(names_from = R.FileName, 
              values_from = mean_quantity) %>%
    suppressMessages()
  z <- y %>% 
  mutate(na_nbr = rowSums(is.na(y[-1]))) %>%
  mutate(mean_quantity = rowMeans(y[2:ncol(y)], na.rm = TRUE)) %>%
  mutate(filtered = !na_nbr <= 1) %>% 
  select(-na_nbr) %>% 
  suppressMessages("`summarise()` has grouped output by 'R.FileName'. You can override using the `.groups` argument.")
  message("Highlighted ", sum(z$filtered), " peptide(s) found in less than ", ncol(y) -2, " replicates")
  
 return(z) }

```

LCM
```{r}
#188
LITDIA_Enhanced_20SPD_45w_188 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_188)
#375
LITDIA_Enhanced_20SPD_45w_375 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_375)
#750
LITDIA_Enhanced_20SPD_45w_750 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_750)
#1500
LITDIA_Enhanced_20SPD_45w_1500 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_1500)
#3000
LITDIA_Enhanced_20SPD_45w_3000 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_3000)
#6000
LITDIA_Enhanced_20SPD_45w_6000 <-  filter_pep(LITDIA_Enhanced_20SPD_45w_6000)
```

HeLa
```{r}
LITDIA_Enhanced_40SPD_40w_1ng_SN16 <- filter_pep(LITDIA_Enhanced_40SPD_40w_1ng_SN16)
LITDIA_Enhanced_40SPD_40w_5ng_SN16 <- filter_pep(LITDIA_Enhanced_40SPD_40w_5ng_SN16)
LITDIA_Enhanced_40SPD_40w_10ng_SN16 <- filter_pep(LITDIA_Enhanced_40SPD_40w_10ng_SN16)
```

# Detect the number of identified peptides
```{r}
LITDIA_Enhanced_20SPD_45w_188_id <- LITDIA_Enhanced_20SPD_45w_375_id <- LITDIA_Enhanced_20SPD_45w_750_id <- LITDIA_Enhanced_20SPD_45w_1500_id <- LITDIA_Enhanced_20SPD_45w_3000_id <- LITDIA_Enhanced_20SPD_45w_6000_id <-id_LITDIA_Enhanced_40SPD_40w_1ng_SN16 <- id_LITDIA_Enhanced_40SPD_40w_5ng_SN16 <- id_LITDIA_Enhanced_40SPD_40w_10ng_SN16 <-rep(NA, 3)
```

LCM
188
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_188_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_188[, i]))}
```
375
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_375_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_375[, i]))}
```
750
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_750_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_750[, i]))}
```
1500
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_1500_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_1500[, i]))}
```
3000
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_3000_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_3000[, i]))}
```
6000
```{r}
for(i in 2:4){
  LITDIA_Enhanced_20SPD_45w_6000_id[i-1] <- sum(!is.na(LITDIA_Enhanced_20SPD_45w_6000[, i]))}
```

HeLa
1ng
```{r}
for(i in 2:5){
  id_LITDIA_Enhanced_40SPD_40w_1ng_SN16[i-1] <- sum(!is.na(LITDIA_Enhanced_40SPD_40w_1ng_SN16[, i]))}
```
5ng
```{r}
for(i in 2:5){
  id_LITDIA_Enhanced_40SPD_40w_5ng_SN16[i-1] <- sum(!is.na(LITDIA_Enhanced_40SPD_40w_5ng_SN16[, i]))}
```
10ng
```{r}
for(i in 2:5){
  id_LITDIA_Enhanced_40SPD_40w_10ng_SN16[i-1] <- sum(!is.na(LITDIA_Enhanced_40SPD_40w_10ng_SN16[, i]))}
```

# Complement the table
```{r}
compute_CV <- function(x){
  y <- x %>% 
    mutate(sd = apply(x[, 2:(ncol(x)-2)],
                      FUN = sd, MARGIN =  1, na.rm = TRUE),
           CV = sd/mean_quantity)
  colnames(y)[2:(ncol(x)-2)] <- paste0("S", 1:(ncol(x)-3))
  if(ncol(x) <= 6){
  y$S4 <- NA
 }
  return(y)
}
```

LCM
```{r}
#188
LITDIA_Enhanced_20SPD_45w_188_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_188)
LITDIA_Enhanced_20SPD_45w_188_cv$input<- "16"
LITDIA_Enhanced_20SPD_45w_188_cv$method<- "Clinical samples"
#375
LITDIA_Enhanced_20SPD_45w_375_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_375)
LITDIA_Enhanced_20SPD_45w_375_cv$input<- "32"
LITDIA_Enhanced_20SPD_45w_375_cv$method<- "Clinical samples"
#750
LITDIA_Enhanced_20SPD_45w_750_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_750)
LITDIA_Enhanced_20SPD_45w_750_cv$input<- "65"
LITDIA_Enhanced_20SPD_45w_750_cv$method<- "Clinical samples"
#1500
LITDIA_Enhanced_20SPD_45w_1500_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_1500)
LITDIA_Enhanced_20SPD_45w_1500_cv$input<- "131"
LITDIA_Enhanced_20SPD_45w_1500_cv$method<- "Clinical samples"
#3000
LITDIA_Enhanced_20SPD_45w_3000_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_3000)
LITDIA_Enhanced_20SPD_45w_3000_cv$input<- "360"
LITDIA_Enhanced_20SPD_45w_3000_cv$method<- "Clinical samples"
#6000
LITDIA_Enhanced_20SPD_45w_6000_cv <- compute_CV(LITDIA_Enhanced_20SPD_45w_6000)
LITDIA_Enhanced_20SPD_45w_6000_cv$input<- "525"
LITDIA_Enhanced_20SPD_45w_6000_cv$method<- "Clinical samples"
```

HeLa
```{r}
LITDIA_Enhanced_40SPD_40w_1ng_SN16_cv <- compute_CV(LITDIA_Enhanced_40SPD_40w_1ng_SN16)
LITDIA_Enhanced_40SPD_40w_1ng_SN16_cv$input<- "4"
LITDIA_Enhanced_40SPD_40w_1ng_SN16_cv$method<- "HeLa samples"

LITDIA_Enhanced_40SPD_40w_5ng_SN16_cv <- compute_CV(LITDIA_Enhanced_40SPD_40w_5ng_SN16)
LITDIA_Enhanced_40SPD_40w_5ng_SN16_cv$input<- "20"
LITDIA_Enhanced_40SPD_40w_5ng_SN16_cv$method<- "HeLa samples"

LITDIA_Enhanced_40SPD_40w_10ng_SN16_cv <- compute_CV(LITDIA_Enhanced_40SPD_40w_10ng_SN16)
LITDIA_Enhanced_40SPD_40w_10ng_SN16_cv$input<- "40"
LITDIA_Enhanced_40SPD_40w_10ng_SN16_cv$method<- "HeLa samples"
```

# Join
```{r}
id_dvp <- 
  rbind(LITDIA_Enhanced_20SPD_45w_188_cv, LITDIA_Enhanced_20SPD_45w_375_cv, LITDIA_Enhanced_20SPD_45w_750_cv, LITDIA_Enhanced_20SPD_45w_1500_cv, LITDIA_Enhanced_20SPD_45w_3000_cv, LITDIA_Enhanced_20SPD_45w_6000_cv, LITDIA_Enhanced_40SPD_40w_1ng_SN16_cv,LITDIA_Enhanced_40SPD_40w_5ng_SN16_cv, LITDIA_Enhanced_40SPD_40w_10ng_SN16_cv)
id_dvp$input %>% table()
id_dvp$method %>% table() 

id_dvp$input <- factor(id_dvp$input, 
                          levels = unique(id_dvp$input))
id_dvp$method <- factor(id_dvp$method, 
                          levels = unique(id_dvp$method))
id_dvp$CV_filter <- NA
id_dvp$CV_filter[id_dvp$CV < 0.1] <- "3"
id_dvp$CV_filter[id_dvp$CV >= 0.1 & id_dvp$CV <= 0.15] <- "2"
id_dvp$CV_filter[id_dvp$CV > 0.15] <- "1"

id_dvp <- id_dvp %>%
  filter(!is.na(CV_filter)) %>% 
  group_by(input, CV_filter, method) %>% 
  summarise(id_S1 = sum(!is.na(S1)),
            id_S2 = sum(!is.na(S2)),
            id_S3 = sum(!is.na(S3)),
            id_S4 = sum(!is.na(S4)))
id_dvp$id_S4[id_dvp$id_S4 == 0] <- NA 

id_dvp$mean_id <- rowMeans(id_dvp[4:6], na.rm = TRUE)
id_dvp$sd_id <- apply(id_dvp[4:6], FUN =  sd, MARGIN = 1, na.rm = TRUE)
```

# Plot 
LCM
```{r}
id_dvp$y_errorbar <- id_dvp$mean_id
id_dvp$y_errorbar[id_dvp$CV_filter == "1"] <-
  id_dvp$y_errorbar[id_dvp$CV_filter == "1"] +
  id_dvp$y_errorbar[id_dvp$CV_filter == "2"]+
  id_dvp$y_errorbar[id_dvp$CV_filter == "3"]
id_dvp$y_errorbar[id_dvp$CV_filter == "2"] <-
  id_dvp$y_errorbar[id_dvp$CV_filter == "2"]+
  id_dvp$y_errorbar[id_dvp$CV_filter == "3"]

plot_lcm <- id_dvp %>% filter(input != "525") %>% filter(input != "360") %>% filter(input != "131")  %>% filter (method == "Clinical samples") %>%
  ggplot(aes(x = input, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7) +
  labs(x = "Cell number LCM",
       y = "Identified peptides",
       fill = "CV") +
  theme_bw() +
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 27),
        strip.text = element_text(size = 27),
        legend.position = c(0.2,0.87),
        legend.background = element_blank(),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.title.y = element_text(vjust = 2.2),
        axis.text.x = element_text(angle = 90, vjust = 0.3, hjust = 1),
        legend.title = element_text(size = 27),
        axis.title.x = element_text(vjust = 0.2),
        legend.text = element_text(size = 27),
        legend.key.size = unit(0.9, "cm"))+
  scale_fill_manual(values = c("grey82", "#FF9090", "#FF3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
    geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.15,
                    size = 0.9)

```

HeLa
```{r}
id_dvp$y_errorbar <- id_dvp$mean_id
id_dvp$y_errorbar[id_dvp$CV_filter == "1"] <-
  id_dvp$y_errorbar[id_dvp$CV_filter == "1"] +
  id_dvp$y_errorbar[id_dvp$CV_filter == "2"]+
  id_dvp$y_errorbar[id_dvp$CV_filter == "3"]
id_dvp$y_errorbar[id_dvp$CV_filter == "2"] <-
  id_dvp$y_errorbar[id_dvp$CV_filter == "2"]+
  id_dvp$y_errorbar[id_dvp$CV_filter == "3"]

plot_hela <- id_dvp %>% filter(input != "525") %>% filter(input != "360") %>% filter(input != "131")  %>% filter (method != "Clinical samples") %>%
  ggplot(aes(x = input, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7) +
  labs(x = "Cell number HeLa",
       y = "Identified peptides",
       fill = "CV") +
  theme_bw() +
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 27),
        strip.text = element_text(size = 27),
        legend.position = "none",
        legend.background = element_blank(),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.3, hjust = 1),
        legend.title = element_text(size = 27),
        axis.title.x = element_text(vjust = 0.2),
        legend.text = element_text(size = 27),
        legend.key.size = unit(0.9, "cm"))+
  scale_fill_manual(values = c("grey82", "#FF9090", "#FF3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
    geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.15,
                    size = 0.9)

```

Join LCM and HeLa
```{r}
figure8 <- plot_lcm + plot_hela + plot_layout(widths = c(3,3))
```
