---
title: "Figure 4"
author: "Lukas"
date: '2022-06-20'
output: html_document
---

# Load packages
```{r}
library("tidyverse")
library("psych")
library("pheatmap")
library("ggpubr")
library("patchwork")
library("ghibli")
library("reprex")
library("ggh4x")
library("ggplot2")
lit_path <-"C:/Users/lukwolt/Documents/R/LIT/"
ot_path <-"C:/Users/lukwolt/Documents/R/OT/"
pp_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/"
fig_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/Figures/"
  
ghibli_palettes$YesterdayMedium
```

# Load data
```{r}
LITDIA_Normal_20SPD_60ms <- read.csv2(paste0(lit_path, "20220215_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV45_60ms.csv"))

LITDIA_Normal_20SPD_80ms <- read.csv2(paste0(lit_path, "20220215_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV45_80ms.csv"))

LITDIA_Normal_20SPD_100ms <- read.csv2(paste0(lit_path, "20220215_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV45_100ms.csv"))

LITDIA_Normal_20SPD_38ms <- read.csv2(paste0(lit_path, "20220525_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV45_auto.csv"))
```

# Remove peptides found in less than 3 replicates
```{r}
filter_pep <- function(x) {
  x$FG.Quantity[as.logical(x$EG.IsImputed)] <- NA
  y <- x %>% 
  group_by(R.FileName, PEP.StrippedSequence) %>% 
  summarise(mean_quantity = mean(FG.Quantity, na.rm = TRUE)) %>%  
  pivot_wider(names_from = R.FileName, 
              values_from = mean_quantity) %>%
    suppressMessages()
  z <- y %>% 
  mutate(na_nbr = rowSums(is.na(y[-1]))) %>%
  mutate(mean_quantity = rowMeans(y[2:ncol(y)], na.rm = TRUE)) %>%
  mutate(filtered = !na_nbr <= 1) %>% 
  select(-na_nbr) %>% 
  suppressMessages("`summarise()` has grouped output by 'R.FileName'. You can override using the `.groups` argument.")
  message("
Highlighted ", sum(z$filtered) , " peptide(s) found in less than ", ncol(y) -2, " replicates")
  
  return(z)
}
```

```{r}
LITDIA_Normal_20SPD_60ms <- filter_pep(LITDIA_Normal_20SPD_60ms)
LITDIA_Normal_20SPD_80ms <- filter_pep(LITDIA_Normal_20SPD_80ms)
LITDIA_Normal_20SPD_100ms <- filter_pep(LITDIA_Normal_20SPD_100ms)
LITDIA_Normal_20SPD_38ms <- filter_pep(LITDIA_Normal_20SPD_38ms)
```

# Detect the number of identified peptides
```{r}
id_LITDIA_Normal_20SPD_60ms <- id_LITDIA_Normal_20SPD_80ms <- 
  id_LITDIA_Normal_20SPD_100ms <- id_LITDIA_Normal_20SPD_38ms <-
  rep(NA, 4)
```

```{r}
for(i in 2:(ncol(LITDIA_Normal_20SPD_60ms)-2)){
  id_LITDIA_Normal_20SPD_60ms[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_60ms[, i]))}
```

```{r}
for(i in 2:(ncol(LITDIA_Normal_20SPD_80ms)-2)){
  id_LITDIA_Normal_20SPD_80ms[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_80ms[, i]))}
```

```{r}
for(i in 2:(ncol(LITDIA_Normal_20SPD_100ms)-2)){
  id_LITDIA_Normal_20SPD_100ms[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_100ms[, i]))}
```

```{r}
for(i in 2:(ncol(LITDIA_Normal_20SPD_38ms)-2)){
  id_LITDIA_Normal_20SPD_38ms[i-1] <- sum(!is.na(LITDIA_Normal_20SPD_38ms[, i]))}
```

# Complement table
```{r}
compute_CV <- function(x){
  y <- x %>% 
    mutate(sd = apply(x[, 2:(ncol(x)-2)],
                      FUN = sd, MARGIN =  1, na.rm = TRUE),
           CV = sd/mean_quantity)
  colnames(y)[2:(ncol(x)-2)] <- paste0("S", 1:(ncol(x)-3))
  if(ncol(x) <= 6){
  y$S4 <- NA
 }
  return(y)
}
```

```{r}
LITDIA_Normal_20SPD_38ms_CV <- compute_CV(LITDIA_Normal_20SPD_38ms)
LITDIA_Normal_20SPD_38ms_CV$IT <- "38ms"

LITDIA_Normal_20SPD_60ms_CV <- compute_CV(LITDIA_Normal_20SPD_60ms)
LITDIA_Normal_20SPD_60ms_CV$IT <- "60ms"

LITDIA_Normal_20SPD_80ms_CV <- compute_CV(LITDIA_Normal_20SPD_80ms)
LITDIA_Normal_20SPD_80ms_CV$IT <- "80ms"

LITDIA_Normal_20SPD_100ms_CV <- compute_CV(LITDIA_Normal_20SPD_100ms)
LITDIA_Normal_20SPD_100ms_CV$IT <- "100ms"
```

# Join
```{r}
CV_figure4 <- 
  rbind(LITDIA_Normal_20SPD_38ms_CV, LITDIA_Normal_20SPD_60ms_CV, 
        LITDIA_Normal_20SPD_80ms_CV, LITDIA_Normal_20SPD_100ms_CV)
CV_figure4$IT %>% table()
CV_figure4$IT <- factor(CV_figure4$IT, 
                          levels = c("38ms", "60ms", "80ms", "100ms"))

CV_figure4$CV_filter <- NA

CV_figure4$CV_filter[CV_figure4$CV < 0.1] <- "3"
CV_figure4$CV_filter[CV_figure4$CV >= 0.1 & CV_figure4$CV <= 0.15] <- "2"
CV_figure4$CV_filter[CV_figure4$CV > 0.15] <- "1"

CV_figure4$SPD <- "20 SPD"

CV_figure4 <- CV_figure4 %>%
  filter(!is.na(CV_filter)) %>% 
  group_by(SPD, IT, CV_filter) %>% 
  summarise(id_S1 = sum(!is.na(S1)),
            id_S2 = sum(!is.na(S2)),
            id_S3 = sum(!is.na(S3)),
            id_S4 = sum(!is.na(S4)))

CV_figure4$mean_id <- rowMeans(CV_figure4[4:7], na.rm = TRUE)
CV_figure4$sd_id <- apply(CV_figure4[4:7], FUN =  sd, MARGIN = 1, na.rm = TRUE)
```

# Plot 
```{r}
CV_figure4$y_errorbar <- CV_figure4$mean_id
CV_figure4$y_errorbar[CV_figure4$CV_filter == "1"] <-
  CV_figure4$y_errorbar[CV_figure4$CV_filter == "1"] +
  CV_figure4$y_errorbar[CV_figure4$CV_filter == "2"]+
  CV_figure4$y_errorbar[CV_figure4$CV_filter == "3"]
CV_figure4$y_errorbar[CV_figure4$CV_filter == "2"] <-
  CV_figure4$y_errorbar[CV_figure4$CV_filter == "2"]+
  CV_figure4$y_errorbar[CV_figure4$CV_filter == "3"]

figure4 <- CV_figure4 %>% 
  ggplot(aes(x = IT, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7) +
  facet_grid(~SPD) +
  labs(x = "Injection Time",
       y = "Identified peptides",
       fill = "CV") +
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 22),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.text.x = element_text(hjust = 0.62),
        axis.title.y = element_text(vjust = 2.2),
        legend.title = element_text(size = 27),
        legend.text = element_text(size = 22),
        legend.key.size = unit(0.9, "cm"),
        axis.title.x = element_text(vjust = -1),
        plot.margin = margin(b = 20,
                             l = 20))+
  scale_fill_manual(values = c("grey82", "#ff9090", "#ff3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
  scale_y_continuous(limits = c(0, 8000)) +
  geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.2,
                    size = 1)

figure4
cairo_pdf(filename = "fig4.pdf", width = 9.9, height = 8.65)
figure4
dev.off()
```
