---
title: "FigureX"
author: "Lukas"
date: '2022-06-20'
output: html_document
---
# Load packages
```{r}
library("tidyverse")
library("psych")
library("pheatmap")
library("ggpubr")
library("patchwork")
library("ghibli")
library("reprex")
library("ggh4x")
library("ggplot2")
lit_path <-"C:/Users/lukwolt/Documents/R/LIT/"
ot_path <-"C:/Users/lukwolt/Documents/R/OT/"
pp_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/"
fig_path <- "C:/Users/lukwolt/Documents/R/Points_across_a_peak/Figures/"
  
ghibli_palettes$YesterdayMedium
```

# Load packages
```{r}
library("tidyverse")
library("UpSetR")
library("patchwork")
library("ggpubr")
library("ggpointdensity")
library("kableExtra")
library("ggupset")
library("pheatmap")
library("robustbase")
library("fmsb")
library("ggrepel")

#set bw theme as default theme
theme_set(theme_bw())
```

# Load Data
40 SPD
```{r}
#38ms 34w
LITDIA_Rapid_40SPD_23ms_40w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Rapid_DIA_1ng_40SPD_whisper100_1CV_auto_34w.csv"))

#31ms 34w
LITDIA_Rapid_40SPD_31ms_34w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Rapid_DIA_1ng_40SPD_whisper100_1CV_31ms_34w.csv"))

#31ms 25w
LITDIA_Rapid_40SPD_31ms_25w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Rapid_DIA_1ng_40SPD_whisper100_1CV_31ms_25w.csv"))

#30ms 30w
LITDIA_Rapid_40SPD_30ms_30w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Rapid_DIA_1ng_40SPD_whisper100_1CV_30ms_30w.csv"))
```

20 SPD
```{r}
#76ms 20w
LITDIA_Normal_20SPD_76ms_20w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_76ms_20w.csv"))

#50ms 30w
LITDIA_Normal_20SPD_50ms_30w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_50ms_30w.csv"))

#38ms 40w
LITDIA_Normal_20SPD_38ms_40w_1 <- read.csv2(paste0(lit_path, "20220509_LIT_Normal_DIA_1ng_20SPD_whisper100_1CV_38ms_40w.csv"))
```


# Remove peptides found in less than 3 replicates
```{r}
filter_pep <- function(x) {
  x$FG.Quantity[as.logical(x$EG.IsImputed)] <- NA
  y <- x %>% 
  group_by(R.FileName, PEP.StrippedSequence) %>% 
  summarise(mean_quantity = mean(FG.Quantity, na.rm = TRUE)) %>%  
  pivot_wider(names_from = R.FileName, 
              values_from = mean_quantity) %>%
    suppressMessages()
  z <- y %>% 
  mutate(na_nbr = rowSums(is.na(y[-1]))) %>%
  mutate(mean_quantity = rowMeans(y[2:ncol(y)], na.rm = TRUE)) %>%
  mutate(filtered = !na_nbr <= 1) %>% 
  select(-na_nbr) %>% 
  suppressMessages("`summarise()` has grouped output by 'R.FileName'. You can override using the `.groups` argument.")
  message("
Highlighted ", sum(z$filtered) , " peptide(s) found in less than ", ncol(y) -2, " replicates")
  
  return(z)
}
```

40 SPD
```{r}
LITDIA_Rapid_40SPD_23ms_40w_1 <- filter_pep(LITDIA_Rapid_40SPD_23ms_40w_1)
LITDIA_Rapid_40SPD_31ms_34w_1 <- filter_pep(LITDIA_Rapid_40SPD_31ms_34w_1)
LITDIA_Rapid_40SPD_31ms_25w_1 <- filter_pep(LITDIA_Rapid_40SPD_31ms_25w_1)
LITDIA_Rapid_40SPD_30ms_30w_1 <- filter_pep(LITDIA_Rapid_40SPD_30ms_30w_1)
```

20 SPD
```{r}
LITDIA_Normal_20SPD_76ms_20w_1 <- filter_pep(LITDIA_Normal_20SPD_76ms_20w_1)
LITDIA_Normal_20SPD_50ms_30w_1 <- filter_pep(LITDIA_Normal_20SPD_50ms_30w_1)
LITDIA_Normal_20SPD_38ms_40w_1 <- filter_pep(LITDIA_Normal_20SPD_38ms_40w_1)
```

# Complement table
```{r}
compute_CV <- function(x){
  y <- x %>% 
    mutate(sd = apply(x[, 2:(ncol(x)-2)],
                      FUN = sd, MARGIN =  1, na.rm = TRUE),
           CV = sd/mean_quantity)
  colnames(y)[2:(ncol(x)-2)] <- paste0("S", 1:(ncol(x)-3))
  if(ncol(x) <= 6){
  y$S4 <- NA
 }
  return(y)
}
```

```{r}
LITDIA_Rapid_40SPD_23ms_40w_1_CV <- compute_CV(LITDIA_Rapid_40SPD_23ms_40w_1)
LITDIA_Rapid_40SPD_23ms_40w_1_CV$method <- "23ms_40w"
LITDIA_Rapid_40SPD_23ms_40w_1_CV$SPD <- "40 SPD"

LITDIA_Rapid_40SPD_31ms_34w_1_CV <- compute_CV(LITDIA_Rapid_40SPD_31ms_34w_1)
LITDIA_Rapid_40SPD_31ms_34w_1_CV$method <- "31ms_34w"
LITDIA_Rapid_40SPD_31ms_34w_1_CV$SPD <- "40 SPD"

LITDIA_Rapid_40SPD_31ms_25w_1_CV <- compute_CV(LITDIA_Rapid_40SPD_31ms_25w_1)
LITDIA_Rapid_40SPD_31ms_25w_1_CV$method <- "31ms_25w"
LITDIA_Rapid_40SPD_31ms_25w_1_CV$SPD <- "40 SPD"

LITDIA_Rapid_40SPD_30ms_30w_1_CV <- compute_CV(LITDIA_Rapid_40SPD_30ms_30w_1)
LITDIA_Rapid_40SPD_30ms_30w_1_CV$method <- "30ms_30w"
LITDIA_Rapid_40SPD_30ms_30w_1_CV$SPD <- "40 SPD"
```

# 20 SPD
```{r}
LITDIA_Normal_20SPD_76ms_20w_1_CV <- compute_CV(LITDIA_Normal_20SPD_76ms_20w_1)
LITDIA_Normal_20SPD_76ms_20w_1_CV$method <- "76ms_20w"
LITDIA_Normal_20SPD_76ms_20w_1_CV$SPD <- "20 SPD"

LITDIA_Normal_20SPD_50ms_30w_1_CV <- compute_CV(LITDIA_Normal_20SPD_50ms_30w_1)
LITDIA_Normal_20SPD_50ms_30w_1_CV$method <- "50ms_30w"
LITDIA_Normal_20SPD_50ms_30w_1_CV$SPD <- "20 SPD"

LITDIA_Normal_20SPD_38ms_40w_1_CV <- compute_CV(LITDIA_Normal_20SPD_38ms_40w_1)
LITDIA_Normal_20SPD_38ms_40w_1_CV$method <- "38ms_40w"
LITDIA_Normal_20SPD_38ms_40w_1_CV$SPD <- "20 SPD"
```

# Join 
```{r}
CV_figure3 <- 
  rbind(LITDIA_Rapid_40SPD_23ms_40w_1_CV, LITDIA_Rapid_40SPD_30ms_30w_1_CV, 
        LITDIA_Rapid_40SPD_31ms_34w_1_CV, LITDIA_Rapid_40SPD_31ms_25w_1_CV,
        LITDIA_Normal_20SPD_38ms_40w_1_CV, LITDIA_Normal_20SPD_50ms_30w_1_CV,
        LITDIA_Normal_20SPD_76ms_20w_1_CV)
CV_figure3$method %>% table()

CV_figure3$CV_filter <- NA

CV_figure3$CV_filter[CV_figure3$CV < 0.1] <- "3"
CV_figure3$CV_filter[CV_figure3$CV >= 0.1 & CV_figure3$CV <= 0.15] <- "2"
CV_figure3$CV_filter[CV_figure3$CV > 0.15] <- "1"

CV_figure3 <- CV_figure3 %>%
  filter(!is.na(CV_filter)) %>% 
  group_by(method, CV_filter, SPD) %>% 
  summarise(id_S1 = sum(!is.na(S1)),
            id_S2 = sum(!is.na(S2)),
            id_S3 = sum(!is.na(S3)),
            id_S4 = sum(!is.na(S4)))
CV_figure3$id_S4[CV_figure3$id_S4 == 0] <- NA
CV_figure3$mean_id <- rowMeans(CV_figure3[4:7], na.rm = TRUE)
CV_figure3$sd_id <- apply(CV_figure3[4:7], FUN =  sd, MARGIN = 1, na.rm = TRUE)
```

# Plot 
```{r}
CV_figure3$y_errorbar <- CV_figure3$mean_id
CV_figure3$y_errorbar[CV_figure3$CV_filter == "1"] <-
  CV_figure3$y_errorbar[CV_figure3$CV_filter == "1"] +
  CV_figure3$y_errorbar[CV_figure3$CV_filter == "2"]+
  CV_figure3$y_errorbar[CV_figure3$CV_filter == "3"]
CV_figure3$y_errorbar[CV_figure3$CV_filter == "2"] <-
  CV_figure3$y_errorbar[CV_figure3$CV_filter == "2"]+
  CV_figure3$y_errorbar[CV_figure3$CV_filter == "3"]

figure3_40SPD <- CV_figure3 %>% 
  filter(method != "31ms_34w" &
         method != "31ms_25w" &
           SPD == "40 SPD") %>% 
  ggplot(aes(x = method, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7)+
  scale_x_discrete(labels = c("23ms_40w" = "  23ms
40w",
                              "30ms_30w" = "  30ms
30w",
                              "31ms_25w" = "  31ms
25w"))+
  facet_grid(~SPD)+
  labs(x = "Method",
       y = "Identified peptides",
       fill = "CV < 20%")+
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 22),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.text.x = element_text(hjust = 0.62),
        axis.title.y = element_text(vjust = 2.2),
        legend.title = element_text(size = 27),
        legend.text = element_text(size = 22),
        legend.key.size = unit(0.9, "cm"),
        axis.title.x = element_text(vjust = -1),
        plot.margin = margin(b = 20,
                             l = 20))+
  scale_fill_manual(values = c("grey82", "#ff9090", "#ff3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
  scale_y_continuous(limits = c(0, 8000)) +
  geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.2,
                    size = 1)

figure3_20SPD <- CV_figure3 %>% 
  filter(SPD == "20 SPD") %>% 
  ggplot(aes(x = method, y = mean_id, fill = CV_filter))+
  geom_col(width = 0.7)+
  scale_x_discrete(labels = c("38ms_40w" = "  38ms
40w",
                              "50ms_30w" = "  50ms
30w",
                              "76ms_20w" = "  76ms
20w"))+
  facet_grid(~SPD)+
  labs(x = "Injection Time & Number of Windows",
       y = "Identidied peptides",
       fill = "CV")+
  theme(axis.text = element_text(size = 24),
        axis.title = element_text(size = 22),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        axis.text.x = element_text(hjust = 0.62),
        axis.title.y = element_text(vjust = 2.2),
        legend.title = element_text(size = 27),
        legend.text = element_text(size = 22),
        legend.key.size = unit(0.9, "cm"),
        axis.title.x = element_text(vjust = -1),
        plot.margin = margin(b = 20,
                             l = 20))+
  scale_fill_manual(values = c("grey82", "#ff9090", "#ff3030"),
                    labels = c("\U2265 15%", "10 - 15%", "< 10%" ))+
  scale_y_continuous(limits = c(0, 8000)) +
  geom_errorbar(aes(ymin = y_errorbar - sd_id, 
                         ymax = y_errorbar + sd_id),
                    width = 0.2,
                    size = 1)
```

```{r}
limit <- c(min(c(layer_scales(figure3_40SPD)$y$get_limits(),
                 layer_scales(figure3_20SPD)$y$get_limits())),
           max(c(layer_scales(figure3_40SPD)$y$get_limits(),
                 layer_scales(figure3_20SPD)$y$get_limits()))+500)

figure3 <- 
  (((figure3_40SPD + 
    scale_y_continuous(limits = limit) +
     theme(axis.title.x = element_blank(),
           legend.position = 'none')
    + plot_layout(widths = c(2,3))) +
  (figure3_20SPD + 
     scale_y_continuous(limits = limit) +
    theme(axis.title.x = element_text(hjust = -0.5, vjust = -1),
           axis.text.y = element_blank(),
           axis.ticks.y = element_blank(),
          axis.title.y = element_blank()))))

figure3
```

