---
title: "Figure6"
author: "Lukas"
date: '2022-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library("tidyverse")
library("UpSetR")
library("patchwork")
library("ggpubr")
library("ggpointdensity")
library("kableExtra")
library("ggupset")
library("pheatmap")
library("robustbase")
library("fmsb")
library("ggrepel")

#set bw theme as default theme
theme_set(theme_bw())

teera_palette <- c("#EEB9CF","#DF7FA7","#D35087","#EAACC6",
                   "#C9D7F0","#7F9FDB","#527DCE","#ADC2E8")
```

# Load data
1 ng
```{r}
pp_Turbo_40SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Turbo_DIA_1ng_40SPD_1CV.tsv"), sep = "/")
pp_Turbo_40SPD_1$indiv <- "Turbo_40SPD_1_"

pp_Rapid_40SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_1ng_40SPD_1CV.tsv"), sep = "/")
pp_Rapid_40SPD_1$indiv <- "Rapid_40SPD_1_"

pp_Normal_40SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_1ng_40SPD_1CV.tsv"), sep = "/")
pp_Normal_40SPD_1$indiv <- "Normal_40SPD_1_"

pp_Rapid_20SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_1ng_20SPD_1CV.tsv"), sep = "/")
pp_Rapid_20SPD_1$indiv <- "Rapid_20SPD_1_"

pp_Normal_20SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_1ng_20SPD_1CV.tsv"), sep = "/")
pp_Normal_20SPD_1$indiv <- "Normal_20SPD_1_"

pp_Enhanced_20SPD_1 <- read.csv2(paste0(pp_path, "PPP_LIT_Enhanced_DIA_1ng_20SPD_1CV.tsv"), sep = "/")
pp_Enhanced_20SPD_1$indiv <- "Enhanced_20SPD_1_"
```

5 ng
```{r}
pp_Turbo_40SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Turbo_DIA_5ng_40SPD_1CV.tsv"), sep = "/")
pp_Turbo_40SPD_5$indiv <- "Turbo_40SPD_5_"

pp_Rapid_40SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_5ng_40SPD_1CV.tsv"), sep = "/")
pp_Rapid_40SPD_5$indiv <- "Rapid_40SPD_5_"

pp_Normal_40SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_5ng_40SPD_1CV.tsv"), sep = "/")
pp_Normal_40SPD_5$indiv <- "Normal_40SPD_5_"

pp_Rapid_20SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_5ng_20SPD_1CV.tsv"), sep = "/")
pp_Rapid_20SPD_5$indiv <- "Rapid_20SPD_5_"

pp_Normal_20SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_5ng_20SPD_1CV.tsv"), sep = "/")
pp_Normal_20SPD_5$indiv <- "Normal_20SPD_5_"

pp_Enhanced_20SPD_5 <- read.csv2(paste0(pp_path, "PPP_LIT_Enhanced_DIA_5ng_20SPD_1CV.tsv"), sep = "/")
pp_Enhanced_20SPD_5$indiv <- "Enhanced_20SPD_5_"
```

10 ng
```{r}
pp_Turbo_40SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Turbo_DIA_10ng_40SPD_1CV.tsv"), sep = "/")
pp_Turbo_40SPD_10$indiv <- "Turbo_40SPD_10_"

pp_Rapid_40SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_10ng_40SPD_1CV.tsv"), sep = "/")
pp_Rapid_40SPD_10$indiv <- "Rapid_40SPD_10_"

pp_Normal_40SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_10ng_40SPD_1CV.tsv"), sep = "/")
pp_Normal_40SPD_10$indiv <- "Normal_40SPD_10_"

pp_Rapid_20SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_10ng_20SPD_1CV.tsv"), sep = "/")
pp_Rapid_20SPD_10$indiv <- "Rapid_20SPD_10_"

pp_Normal_20SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_10ng_20SPD_1CV.tsv"), sep = "/")
pp_Normal_20SPD_10$indiv <- "Normal_20SPD_10_"

pp_Enhanced_20SPD_10 <- read.csv2(paste0(pp_path, "PPP_LIT_Enhanced_DIA_10ng_20SPD_1CV.tsv"), sep = "/")
pp_Enhanced_20SPD_10$indiv <- "Enhanced_20SPD_10_"
```


100 ng
```{r}
pp_Turbo_40SPD_100 <- read.csv2(paste0(pp_path, "PPP_LIT_Turbo_DIA_100ng_40SPD_1CV.tsv"), sep = "/")
pp_Turbo_40SPD_100$indiv <- "Turbo_40SPD_100_"

pp_Rapid_40SPD_100 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_100ng_40SPD_1CV.tsv"), sep = "/")
pp_Rapid_40SPD_100$indiv <- "Rapid_40SPD_100_"

pp_Normal_40SPD_100 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_100ng_40SPD_1CV.tsv"), sep = "/")
pp_Normal_40SPD_100$indiv <- "Normal_40SPD_100_"

pp_Rapid_20SPD_100 <- read.csv2(paste0(pp_path, "PPP_LIT_Rapid_DIA_100ng_20SPD_1CV.tsv"), sep = "/")
pp_Rapid_20SPD_100$indiv <- "Rapid_20SPD_100_"

pp_Normal_20SPD_100 <- read.csv2(paste0(pp_path, "PPP_LIT_Normal_DIA_100ng_20SPD_1CV.tsv"), sep = "/")
pp_Normal_20SPD_100$indiv <- "Normal_20SPD_100_"
```

# Join

```{r}
colnames(pp_Turbo_40SPD_1) <- colnames(pp_Turbo_40SPD_5) <- colnames(pp_Turbo_40SPD_10) <-
  colnames(pp_Turbo_40SPD_100) <- colnames(pp_Rapid_40SPD_1) <- colnames(pp_Rapid_40SPD_5) <-
  colnames(pp_Rapid_40SPD_10) <- colnames(pp_Rapid_40SPD_100) <- colnames(pp_Normal_40SPD_1) <-
  colnames(pp_Normal_40SPD_5) <- colnames(pp_Normal_40SPD_10) <- colnames(pp_Normal_40SPD_100) <-
  colnames(pp_Rapid_20SPD_1) <- colnames(pp_Rapid_20SPD_5) <- colnames(pp_Rapid_20SPD_10) <-
  colnames(pp_Rapid_20SPD_100) <- colnames(pp_Normal_20SPD_1) <- colnames(pp_Normal_20SPD_5) <-
  colnames(pp_Normal_20SPD_10) <- colnames(pp_Normal_20SPD_100) <- colnames(pp_Enhanced_20SPD_1) <-
  colnames(pp_Enhanced_20SPD_5) <- colnames(pp_Enhanced_20SPD_10) <-
  c("Points_per_Peaks", "indiv")

pp <- rbind(pp_Turbo_40SPD_1, pp_Turbo_40SPD_5, pp_Turbo_40SPD_10, pp_Turbo_40SPD_100,
            pp_Rapid_40SPD_1, pp_Rapid_40SPD_5, pp_Rapid_40SPD_10, pp_Rapid_40SPD_100,
            pp_Normal_40SPD_1, pp_Normal_40SPD_5, pp_Normal_40SPD_10, pp_Normal_40SPD_100,
            pp_Rapid_20SPD_1, pp_Rapid_20SPD_5, pp_Rapid_20SPD_10, pp_Rapid_20SPD_100, 
            pp_Normal_20SPD_1, pp_Normal_20SPD_5, pp_Normal_20SPD_10, pp_Normal_20SPD_100,
            pp_Enhanced_20SPD_1, pp_Enhanced_20SPD_5, pp_Enhanced_20SPD_10)

pp$input <- NA
pp$input[grepl("1_", pp$indiv)] <- "1 ng"
pp$input[grepl("5_", pp$indiv)] <- "5 ng"
pp$input[grepl("10_", pp$indiv)] <- "10 ng"
pp$input[grepl("100_", pp$indiv)] <- "100 ng"
pp$input <- factor(pp$input, levels = unique(pp$input))

pp$IT <- NA
pp$IT[grepl("20SPD", pp$indiv)] <- "20 SPD"
pp$IT[grepl("40SPD", pp$indiv)] <- "40 SPD"
pp$IT <- factor(pp$IT, levels = c("40 SPD", "20 SPD"))

pp$method <- NA
pp$method[grepl("Turbo", pp$indiv)] <- "Turbo"
pp$method[grepl("Rapid", pp$indiv)] <- "Rapid"
pp$method[grepl("Normal", pp$indiv)] <- "Normal"
pp$method[grepl("Enhanced", pp$indiv)] <- "Enhanced"
pp$method <- factor(pp$method, levels = c("Turbo", "Rapid", "Normal", "Enhanced"))

```

# Plot A
```{r}
palette1 <-c("#C8F5FF", "#75CFFF", "#B3E4FF") 

plot_40SPD <- pp %>%
  filter(IT == "40 SPD" &
           input != "100 ng") %>% 
  ggplot(aes(x = input, y = Points_per_Peaks,
             fill = as.factor(indiv)))+
  scale_y_log10()+
  geom_violin(draw_quantiles = 0.5) +
  scale_fill_manual(values = rep(palette1,3)) +
  facet_grid(IT ~ method)+
  geom_hline(yintercept = 6,
             linetype = "dashed") +
  labs(title = "A")+
  theme(legend.position = "none",
        axis.text = element_text(size = 24),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        plot.margin = margin(t = 20,  
                             r = 50,
                             b = 20,
                             l = 10),
        plot.title = element_text(size = 32, face = "bold",
                                  hjust = -0.1))
palette2 <- c("#00E5E6", "#009999", "#00CCCC") 

plot_20SPD <- pp %>%
  filter(IT == "20 SPD" &
           input != "100 ng") %>% 
  ggplot(aes(x = input, y = Points_per_Peaks,
             fill = as.factor(indiv)))+
  geom_violin(draw_quantiles = 0.5)+
  scale_y_log10() +
  scale_fill_manual(values = rep(palette2,3)) +
  facet_grid(IT ~ method) +
  geom_hline(yintercept = 6,
             linetype = "dashed") +
  labs(x = "Input",
       y = "Points across a peak") +
  theme(legend.position = "none",
        axis.title = element_text(size = 27),
        axis.text = element_text(size = 24),
        axis.text.x = element_text(angle = 90, vjust = 0.3, hjust = 1),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        plot.margin = margin(t = 15,  
                             r = 50,
                             b = 10,
                             l = 10))

limit <- 10^c(min(c(layer_scales(plot_40SPD)$y$get_limits(), 
                   layer_scales(plot_20SPD)$y$get_limits())),
              max(c(layer_scales(plot_40SPD)$y$get_limits(),
                   layer_scales(plot_20SPD)$y$get_limits())))

figure6a <- (plot_40SPD + 
    scale_y_log10(limits = limit,
                   breaks = c(3, 6, 10, 30))+
    theme(axis.title = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank()))/
  (plot_20SPD + 
     scale_y_log10(limits = limit,
                   breaks = c(3, 6, 10, 30))+
     theme(axis.title.y = element_text(hjust = -1.8, vjust = 1)))
figure6a
```

# Plot B
```{r}
pp$acc <- pp$Points_per_Peaks >= 6

temp1 <- pp %>% 
  group_by(indiv, IT, input, method) %>% 
  summarise(n_prec = sum(!is.na(Points_per_Peaks)))

temp2 <- pp %>% 
  group_by(indiv, IT, input, method) %>% 
  summarise(n_acc = sum(acc))

temp1$Precursors <- "< 6"
temp2$Precursors <- "\U2265 6"

colnames(temp1)[5] <- "n"
colnames(temp2)[5] <- "n"

temp1$n <- temp1$n - temp2$n

temp <- rbind(temp2, temp1)

temp$Precursors <- factor(temp$Precursors, 
                         levels = c("< 6", "\U2265 6"))

id_pr_40SPD <- temp %>% 
  filter(input != "100 ng" & IT == "40 SPD" ) %>% 
  ggplot(aes(x = method, y = n/4, fill = Precursors, group = method)) +
  geom_col() +
  theme_bw() +
  facet_grid(IT ~ input) +
  labs(x = "Scanning mode",
       y = "Precursors number",
       title = "B",
       fill = "Points across a peak")+
  scale_fill_manual(values = c("grey82", "#ff3030"))+
  theme(plot.title = element_text(size = 32, face = "bold",
                                  hjust = -0.095),
        axis.title = element_blank(),
        axis.text = element_text(size = 24),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(size = 27),
        strip.background = element_rect(fill = "#E5E4F7"),
        legend.title = element_text(size = 27, vjust = 1.3),
        legend.text = element_text(size = 22),
        legend.position = "top")

id_pr_20SPD <- temp %>% 
  filter(input != "100 ng" & IT == "20 SPD" ) %>% 
  ggplot(aes(x = method , y = n/4, fill = Precursors, group = method)) +
  geom_col() +
  theme_bw() +
  facet_grid(IT ~ input) +
  labs(x = "Scanning mode",
       y = "Precursors number")+
  scale_fill_manual(values = c("grey82", "#ff3030"))+
  theme(axis.title = element_text(size = 27),
        axis.text = element_text(size = 24),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(size = 27),
        strip.background.x = element_blank(),
        strip.background = element_rect(fill = "#E5E4F7"),
        strip.text.x = element_blank(),
        axis.title.x = element_text(vjust = -1),
        legend.position = "none")

limit <- c(min(c(layer_scales(id_pr_40SPD)$y$get_limits(),
                 layer_scales(id_pr_20SPD)$y$get_limits())),
           max(c(layer_scales(id_pr_40SPD)$y$get_limits(),
                 layer_scales(id_pr_20SPD)$y$get_limits()))+500)
figure6b <-
 (id_pr_40SPD +
    theme(axis.title = element_blank())+
    scale_y_continuous(limits = limit))/
 (id_pr_20SPD +
    theme(axis.title.y = element_text(hjust = -2.15,
                                      vjust = 3.5))+
    scale_y_continuous(limits = limit))
```

# Plot A and B 
```{r}
figure6 <- wrap_plots(figure6a,figure6b, nrow = 2)

cairo_pdf(filename = "fig6.pdf", width = 16.67, height = 18.75,)
figure6 
dev.off()
```
